### ISSUE TITLE
Could not find a package configuration file provided by "Franka"

### ISSUE THREAD

**Issue by Sission** [roboticsleeds/cobot_pump_ros#4]
Can not build. It shows the error message: Could not find a package configuration file provided by "Franka" (requested 0.8.0)

In the Cmakelist, there is:
```
find_package(Franka 0.9.0 QUIET)
if(NOT Franka_FOUND)
  find_package(Franka 0.8.0 REQUIRED)
endif()
```

I am wondering what is "Franka" package? Is this franka_ros?

My system currently runs libfranka 0.9.1, franka_ros 0.8.0, and software system 4.2.1. Could you please help? Thanks!

**Comment by Sission** [comment]
Also, In the Cmakelist, there is:

```
add_executable(cobot_pump
  src/cobot_pump.cpp
)

target_link_libraries(cobot_pump
  ${Franka_LIBRARIES}
  ${catkin_LIBRARIES}
)

```

, which are not existed in the repo.

**Comment by DMackRus** [comment]
Hello,

The package it is looking for there I believe is franka_ros, have you definitely got that installed on your system? 

For the second issue, yes you are correct, that file no longer, exists that will be fixed sometime soon once my pull request is approved by our admin.

This ROS package is still ongoing work and we are still having issues with it but the most rec3ent version works to control the pump mostly but has some issues with randomly disconnecting from the franka robot.

**Comment by Sission** [comment]
Hi,

Yes, I got the 1st issue solved. For some reason, ROS did not find franka_ros package.

For the 2nd issue, is there any history file I use and try right now, even it does not work perfectly? I'd love to help if I can. I just got the pump installed and desire just to try it. If I can ask, do you know how I can control the pump? I did not find much helpful info from the Franka World community. Thanks for your help!

**Comment by DMackRus** [comment]
Hi, 

you can either clone this repository, however this isn't fully up to date with my improvements yet, or you can go directly to my repository at (https://github.com/DMackRus/cobot_pump_ros) where The ROS package is more up to date. If you read through my read me file it should tell you how to use the pump and the basic_demo.py script shows how you can call the services from a python  script.

**Comment by Sission** [comment]
Hi Thanks!
However I also can not build your personal repo. Here is the error:

```
fatal error: cobot_pump_ros/startPump.h: No such file or directory
   17 | #include "cobot_pump_ros/startPump.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

```

i am guessing this repo also misses some headfiles:
```

#include "cobot_pump_ros/startPump.h"
#include "cobot_pump_ros/stopPump.h"
#include "cobot_pump_ros/dropItem.h"
#include "cobot_pump_ros/readState.h"
#include "cobot_pump_ros/checkItemAttached.h"
```

**Comment by DMackRus** [comment]
no those files should be there, have you ran "catkin_ make" in your catkiin_ws folder? when you do that it runs the cmake.txt file of this projects and will effectively generate those header files (but you wont be able to see them, theyre kind of hidden.)

**Comment by Sission** [comment]
Hi! This was the error message I got after I ran "catkin_make". Here is what I did:

In my catkin_ws/src folder:
`git clone https://github.com/DMackRus/cobot_pump_ros.git`

go back to the catkin_ws folder:
`catkin_make`

After building about 50% it shows the error:
In file included from /home/sission/catkin_ws/src/cobot_pump_ros/src/cobot_pump_node.cpp:3:
```
/home/sission/catkin_ws/src/cobot_pump_ros/include/cobot_pump_node.h:17:10: fatal error: cobot_pump_ros/startPump.h: No such file or directory
   17 | #include "cobot_pump_ros/startPump.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [cobot_pump_ros/CMakeFiles/cobot_pump_node.dir/build.make:63: cobot_pump_ros/CMakeFiles/cobot_pump_node.dir/src/cobot_pump_node.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:4000: cobot_pump_ros/CMakeFiles/cobot_pump_node.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 50%] Built target cobot_pump_ros_generate_messages_py
make: *** [Makefile:141: all] Error 2
Invoking "make -j2 -l2" failed

```

delete your repo and the ws can be built without an issue.

Thank you

**Comment by DMackRus** [comment]
hmmmm, that is weird, I am not in the lab tomorrow unfortunately, I am back in on thursday and will try and clone my repository and see if it works straight from github or if there is something missing and get back to you thursday afternoon

**Comment by Sission** [comment]
Thank you very much and looking forward to it.

**Comment by Sission** [comment]
Hi! I've catkin_make it successfully after I change the CMakelist.txt:

```
add_dependencies(cobot_pump_node
  ${catkin_EXPORTED_TARGETS}
)
```

to

```
add_dependencies(cobot_pump_node
  cobot_pump_ros_generate_messages_cpp
)
```

Also, I did not need to change anything if I catkin_make your repo in the real_time kernel machine which connects with Franka directly. Normally, I will run the roscore in the rt-kernel and use another machine to communicate with it and control it remotely. That being said, I have to change the CMakelist.txt in the remote machine but can be catkin_make without issues in the rt-kernel. Not sure why, they have the same configurations.

I tried to:

`rosrun cobot_pump_ros cobot_pump_node 192.168.126.3` in terminal 1 
and it asks me to input franka ip again:

`franka ip is:`

Then I input it and pressed the enter.

In another terminal 2, I ran:
`rosrun cobot_pump_ros basic_demo.py`

Sadly, it shows the error: Exception thrown while processing service call: libfranka: Connection error: host not find.

Both terminals are running in the rt-kernel machine.

This ip address works perfectly with all other nodes, such as libfranka examples and moveit. Is this the issue you mentioned before?

Thank you!

**Comment by DMackRus** [comment]
Hi, 

Apologies I cant test this today, but can test it tomorrow, I think that rosrun command might be deprecated now for my personal repository code, I use the ROS parameter server to load the franka ip address now instead. I have a launch file somewhere that is not on this repository with the command to launch the pump, but if you just google how to launch a normal node in a launch file using ros parameters I reckon you will be able to get it to work. 

The second issue I would imagine comes from the fact that the server isnt connecting to the robot which hopefully should be fixed by the launch file with the ros parameter.

Failing that I will send you a snippet of my launch file tomorrow. Good luck.

**Comment by Sission** [comment]
Hi! Thanks for letting me know. I haven’t got a chance to go through your
node and demo script yet. I’ll try to figure it out Friday. Thanks for you
help and it would be great if you can share your working files.

**Comment by DMackRus** [comment]
Hi, next time you try to launch the pump, try making a quick launch file and roslaunch it. In the launch file you need a node that looks something like this

<launch>

        <param name="franka_ip" value="192.168.130.1"/>

        <node name="pump_controller" pkg="cobot_pump_ros" type="cobot_pump_node" respawn="false" output="screen"/>
</launch>

Obviously change the ip value to your own ip address for your robot. Let me know if this works and I will make sure to add it to the documentation before it is merged onto our main branch.

**Comment by Sission** [comment]
Hi! Awesome!
It works fine. Thanks!

**Comment by DMackRus** [comment]
Excellent, glad to hear its working!

**Comment by rpapallas** [comment]
Hi all, David's recent changes have now been merged to this repository. If you want to make sure to have the latest changes, make sure to clone this repository instead of the fork. Thank you, @DMackRus, for solving the issues and @Sission for testing the package.
